rest:
    urlBase: http://127.0.0.1
    pathBase: /api/
    # turn off OpenAIRE traffic logging
    handlers:
        methods:
            get: []
            getMetadata: []
doorkeeper:
    epicPid:
        pswd:
    checkRanges: {}